# Generated by Django 6.0.1 on 2026-01-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do barbeiro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('services', models.ManyToManyField(blank=True, related_name='barbers', to='services.service', verbose_name='Serviços')),
            ],
            options={
                'verbose_name': 'Barbeiro',
                'verbose_name_plural': 'Barbeiros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BarberWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Fim')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='barbers.barber')),
            ],
            options={
                'verbose_name': 'Horário de trabalho',
                'verbose_name_plural': 'Horários de trabalho',
                'unique_together': {('barber', 'week_day')},
            },
        ),
    ]
